version: "3.9"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092-9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.79 # replace with your local ip address
      KAFKA_CREATE_TOPICS: "ECOMMERCE_NEW_ORDER:3:2,ECOMMERCE_SEND_EMAIL:3:2,ECOMMERCE_ORDER_APPROVED:3:2,ECOMMERCE_ORDER_REJECTED:3:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock